version: "2"
services:
  node:
    build:
      context: https://github.com/Coinversable/validana-node.git
      dockerfile: Node.Dockerfile
      args:
        NODEVERSION: 10
    restart: unless-stopped
    environment:
      # The processor should have these values for you.
      VNODE_ENCRYPTIONKEY: 
      VNODE_PUBLICKEY: 
      VNODE_PROCESSORHOST: 
      VNODE_PROCESSORPORT: 443
      VNODE_TLS: 'true'
      # Make sure it is the same as the port you expose.
      VNODE_LISTENPORT: 29473
      # Should be the same as database NODEPASS below.
      VNODE_DBPASSWORD: 
      VNODE_DBHOST: database
    ports:
      - "29473:29473"
  database:
    build: 
      context: https://github.com/Coinversable/validana-node.git
      dockerfile: DB.Dockerfile
      args:
        NODEPASS: 
        BACKENDPASS: 
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 
    volumes:
      - blockchain_node:/var/lib/postgresql/data
    expose:
      - "5432"
  server:
    build: 
      context: https://github.com/Coinversable/validana-server.git
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      VSERVER_DBPASSWORD: 
      VSERVER_DBNAME: blockchain_node
      VSERVER_DBHOST: database
      # Make sure it is the same as the port you expose.
      VSERVER_RESTPORT: 80
      # Make sure it is the same as the port you expose.
      VSERVER_WSPORT: 8080
      VSERVER_API: '{"v1": "/usr/node/dist/basics/basichandler.js"}'
      VSERVER_TLS: 'false'
      VSERVER_KEYPATH: ''
      VSERVER_CERTPATH: ''
    ports:
      - "80:80"
      - "8080:8080"

volumes:
  blockchain_node: